### PR TITLE
Update for ide 4.1

### PR DESCRIPTION
**Pull request by sschaef**
Update for 4.1 release.

### CODE REVIEW

**Comment by dragos** [comment]
LGTM

**Comment by mkurz** [comment]
@sschaef @dragos Thanks for all the work on ScalaIDE - you are doing an amazing job!
However I just raised an issue with ScalaIDE: https://scala-ide-portfolio.assembla.com/spaces/scala-ide/support/tickets/1002450
Is there any chance you can have a look at it and hopefully fix it before the 4.1 release? If you need any help let me know.
Thank you very much!

**Comment by sschaef** [comment]
@mkurz I'm going to ship a RC today but I'll have a look to your ticket. If it is a bug that can easily be fixed it still has chances to get into 4.1.

**Comment by mkurz** [comment]
@sschaef Thanks!

**Pull request merged**
